color0 #424659
color1 #ffb4ab
color2 #5fd4fd
color3 #89d0ed
color4 #b7c4ff
color5 #5fd4fd
color6 #89d0ed
color7 #e1e1ef
color8 #8c90a6
color9 #ffb4ab
color10 #5fd4fd
color11 #89d0ed
color12 #b7c4ff
color13 #5fd4fd
color14 #89d0ed
color15 #e1e1ef

cursor                #e1e1ef
cursor_text_color     #11131c
background            #11131c
foreground            #e1e1ef
selection_foreground  #c2c5dd
selection_background  #424659
active_border_color   #5fd4fd
inactive_border_color #424659
url_color             #5fd4fd

active_tab_foreground   #003544
active_tab_background   #5fd4fd
inactive_tab_foreground #c2c5dd
inactive_tab_background #424659
cursor_trail_color      #c2c5dd
